# Change prefix to Ctrl+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Status bar
set -g status-style bg=#1a1b26,fg=#c0caf5
set -g status-left "#[bg=#7aa2f7,fg=#1a1b26,bold] #S #[bg=#1a1b26,fg=#7aa2f7]"
set -g status-right "#[fg=#7aa2f7,bg=#1a1b26]#[bg=#7aa2f7,fg=#1a1b26,bold] %H:%M #[bg=#3d59a1,fg=#1a1b26,bold] %d/%m/%Y "
set -g window-status-format "#[fg=#565f89] #I #W "
set -g window-status-current-format "#[bg=#3d59a1,fg=#c0caf5,bold] #I #W "
set -g status-left-length 100
set -g status-right-length 100


# Auto restore on start
set -g @continuum-restore 'on'

# Initialize tpm (keep at bottom)
run '~/.tmux/plugins/tpm/tpm'
set -g @catppuccin_flavour 'mocha'
